# Database Configuration for Production (Supabase PostgreSQL)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://db.wltfcolsglrpvcacxzbu.supabase.co:5432/postgres}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driverClassName=org.postgresql.Driver

# In production, do not drop or automatically alter the schema
spring.jpa.hibernate.ddl-auto=none
